name: SurvivorBot
version: 0.1
description: Multi server chat system with discord integration, requires a Redis server with default configuration to function
author: Fireblazerrr

main: com.fireblazerrr.survivorbot.SurvivorBot

commands:
  ch:
    description: Manipulate channels
    usage: /channels <args...>
    aliases: channels

permissions:
  

