name: SurvivorBot
version: 0.0.2
description: Multi server chat system with discord integration, requires a Redis server with default configuration to function
author: Fireblazerrr

main: com.fireblazerrr.survivorbot.SurvivorBot

commands:
  ch:
    aliases: ['survivorbot', 'leave', 'join', 'ignore', 'msg', 'tell', 'pm', 'w', 'r', 'afk']
    description: Root Survivorbot command
    usage: /<command>
  me:
    description: Sends emote messages
    usage: /<command> <message>
permissions:
    survivorbot.force.join.all:
        default: false
    survivorbot.force.leave.all:
        default: false
    survivorbot.autojoin.all:
        default: false